import { StyleSheet } from "react-native";

const PRIMARY = "#407BFF";

export const myStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
  },
  card: {
    margin: 10,
    padding: 10,
    // backgroundColor: "lightgray",
    borderRadius: 15,
    // shadowColor: "#001933",
    backgroundColor: "#4287f5",
    width: "90%",
  },
  text: {
    color: "#ffffff",
  },
  splash: {
    backgroundColor: "#4287f5",
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
    width: "100%",
  },
  splashText: {
    color: "white",
    fontSize: 34,
    fontWeight: "bold",
    fontFamily: "",
    fontStyle: "italic",
  },
  flex: { flex: 1 },
  safe: { flex: 1, backgroundColor: "#fff" },
  scroll: {
    flexGrow: 1,
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 24,
  },
  title: {
    fontSize: 32,
    fontWeight: "700",
    color: "#000",
  },
  subtitle: {
    fontSize: 13,
    color: "#111",
    marginTop: 4,
    marginBottom: 36,
  },
  field: { marginBottom: 18 },
  label: {
    fontSize: 13,
    fontWeight: "500",
    color: "#111",
    marginBottom: 8,
  },
  input: {
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#ececec",
    backgroundColor: "#fff",
    paddingHorizontal: 18,
    fontSize: 14,
    color: "#111",
  },
  passwordWrap: { justifyContent: "center" },
  passwordInput: { paddingRight: 48 },
  eye: { position: "absolute", right: 16 },
  button: {
    height: 52,
    borderRadius: 26,
    backgroundColor: "#4287f5",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  buttonDisabled: { backgroundColor: "#555" },
  buttonText: { color: "#fff", fontSize: 14, fontWeight: "600" },
  buttonTextDisabled: { color: "#b5b5b5" },
  forgot: { alignSelf: "center", marginTop: 18 },
  forgotText: { fontSize: 13, color: "#111" },
  footer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 32,
  },
  footerText: { fontSize: 12, color: "#111" },
  footerLink: { fontWeight: "700", color: "#4287f5" },

  // Employee Profile Styles
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerSide: { width: 40 },
  headerRight: { alignItems: "flex-end" },
  headerTitle: { fontSize: 18, fontWeight: "700", color: "#111" },
  scrolll: { paddingHorizontal: 16, paddingBottom: 32 },
  identity: { alignItems: "center", marginTop: 8, marginBottom: 24 },
  avatar: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: PRIMARY,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  avatarText: { color: "#fff", fontSize: 22, fontWeight: "700" },
  name: { fontSize: 14, fontWeight: "700", color: "#111" },
  role: { fontSize: 11, color: "#333", marginTop: 2 },
  // field: { marginBottom: 16 },
  // label: {
  //   fontSize: 13,
  //   fontWeight: "500",
  //   color: "#111",
  //   marginBottom: 8,
  // },
  valueBox: {
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#ececec",
    backgroundColor: "#fff",
    paddingHorizontal: 18,
    justifyContent: "center",
  },
  valueText: { fontSize: 14, color: "#8a8a8a" },
  logout: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 16,
  },
  logoutText: { fontSize: 14, fontWeight: "500", color: PRIMARY },

  //HR Home Styles... extra bottom padding so content clears the floating tab bar
  scrol: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 110 },
  headerHrAdmin: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 20,
  },

  headerText: { flex: 1, paddingRight: 12 },
  greeting: { fontSize: 20, fontWeight: "700", color: "#111" },
  greetingSub: { fontSize: 13, color: "#333", marginTop: 4 },
  bell: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#eef3ff",
    alignItems: "center",
    justifyContent: "center",
  },
  statRow: { flexDirection: "row", gap: 12, marginBottom: 12 },
  statCard: {
    backgroundColor: PRIMARY,
    borderRadius: 20,
    padding: 16,
    justifyContent: "space-between",
  },
  statHalf: { flex: 1, height: 96 },
  statWide: { height: 88 },
  statLabel: { color: "#fff", fontSize: 12 },
  statValue: { color: "#fff", fontSize: 24, fontWeight: "700" },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 24,
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 14, fontWeight: "600", color: "#111" },
  viewAll: { fontSize: 13, fontWeight: "500", color: "#111" },
  activityCard: {
    backgroundColor: "#f3f3f3",
    borderRadius: 20,
    padding: 12,
    gap: 12,
  },
  activityRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  activityIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  activityText: { flex: 1 },
  activityTitle: { fontSize: 14, fontWeight: "600", color: "#111" },
  activitySub: { fontSize: 11, color: "#555", marginTop: 2 },
  activityTime: { fontSize: 11, color: "#555" },
  quickTitle: { marginTop: 24, marginBottom: 12 },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#e6e6e6",
    paddingHorizontal: 18,
    marginBottom: 12,
  },
  actionLabel: {
    flex: 1,
    textAlign: "center",
    fontSize: 14,
    fontWeight: "500",
    color: "#111",
  },

  //HR Add Employee Styles

  // flex: { flex: 1 },
  // safe: { flex: 1, backgroundColor: "#fff" },
  headerAddEmployee: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerTitleHrAddEmployee: { fontSize: 18, fontWeight: "700", color: "#111" },
  scrollHrAddEmployee: { paddingHorizontal: 16, paddingBottom: 32 },
  sectionTitleHrAddEmployee: {
    fontSize: 13,
    fontWeight: "600",
    color: "#111",
    marginTop: 8,
    marginBottom: 14,
  },
  fieldHrAddEmployee: { marginBottom: 14 },
  labelHrAddEmployee: {
    fontSize: 12,
    fontWeight: "500",
    color: "#111",
    marginBottom: 8,
  },
  required: { color: "#d93025" },
  inputWrap: { justifyContent: "center" },
  inputHrAddEmployee: {
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: "#e6e6e6",
    backgroundColor: "#fff",
    paddingHorizontal: 18,
    fontSize: 13,
    color: "#111",
  },
  inputWithIcon: { paddingRight: 44 },
  rightIcon: { position: "absolute", right: 16 },
  select: {
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: "#e6e6e6",
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  selectText: { flex: 1, fontSize: 13, color: "#111" },
  selectPlaceholder: { color: "#9a9a9a" },
  row: { flexDirection: "row", gap: 12 },
  half: { flex: 1 },
  saveButton: {
    height: 52,
    borderRadius: 26,
    backgroundColor: PRIMARY,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
  },
  saveText: { color: "#fff", fontSize: 14, fontWeight: "600" },
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 32,
  },
  sheetTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111",
    marginBottom: 8,
  },
  option: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#e6e6e6",
  },
  optionText: { fontSize: 14, color: "#111" },
  optionSelected: { color: PRIMARY, fontWeight: "600" },
});
